function maxkmask_gui(hObject)
% maxkmask_gui is a internal function of fMROI. It creates the panel
% and uicontrols for calling maxkmask_gui function.
%
% Syntax:
%   maxkmask_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2019, peres.asc@gmail.com
% Last update: Andre Peres, 04/08/2023, peres.asc@gmail.com

handles = guidata(hObject);
%--------------------------------------------------------------------------
% creates the ROIs Panel
fs = 1; % font scale
panelroi_pos = [0.01, 0.01, 0.98, 0.87];

handles.panel_roimethod = uipanel(handles.tab_genroi,...
    'Units','normalized','BackgroundColor','w',...
    'Position',panelroi_pos,'Visible', 'on');

%--------------------------------------------------------------------------
% creates the text for source image
guidata(hObject,handles)
imgname = getselectedimgname(hObject);
imgnamelist = getimgnamelist(hObject);

handles.text_roisrcimagetxt = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','FontWeight','bold',...
    'String','Source image:','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fs*.65,...
    'HorizontalAlignment','left','Position',[.01,.9,.98,.1]);

handles.text_roisrcimage = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String',imgname,...
    'FontUnits','normalized','FontSize',fs*.65,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.8,.98,.1]);

%--------------------------------------------------------------------------
% creates the Radio Button Group in panel_roi  

handles.buttongroup_spheremasktype = uibuttongroup(handles.panel_roimethod,...
    'BackgroundColor', 'w', 'Units', 'normalized',...
    'Position',[.01,.67,.48,.11]);
%--------------------------------------------------------------------------
% creates the spheremasktype radio button radius
handles.radio_sphereradius = uicontrol(...
    handles.buttongroup_spheremasktype,'Style','radiobutton',...
    'Units','normalized','String','Sphere','Position',[0,0,.55,1],...
    'FontUnits','normalized','FontSize',fs*.65,'BackgroundColor','w',...
    'Callback',@radiobutton_masksphere_callback);

%--------------------------------------------------------------------------
% creates the spheremasktype radio button volume
handles.radio_spherevolume = uicontrol(...
    handles.buttongroup_spheremasktype,'Style','radiobutton',...
    'Units','normalized','String','Mask','Position',[.55,0,1,1],...
    'FontUnits','normalized','FontSize',fs*.65,'BackgroundColor','w',...
    'Callback',@radiobutton_maskimage_callback);

%--------------------------------------------------------------------------
% creates the text for number of voxels in the ROI
handles.text_roinvox = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String','Size (voxels):',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.52,.3,.1]);
        
%--------------------------------------------------------------------------
% creates the edit text for number of voxels in the ROI
handles.edit_roinvox = uicontrol(handles.panel_roimethod,...
    'Style','edit','Units','normalized','String','50',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.31,.52,.18,.1]);

%--------------------------------------------------------------------------
% creates the text for radius/volume in voxels
handles.text_roiradius = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String','Radius:',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.38,.3,.1]);
        
        
%--------------------------------------------------------------------------
% creates the edit text for radius/volume in voxels
handles.edit_roiradius = uicontrol(handles.panel_roimethod,...
    'Style','edit','Units','normalized','String','5',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.31,.38,.18,.1]);
        
        
%--------------------------------------------------------------------------
% creates the text for radius/volume in voxels
handles.text_maskimg = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String','Mask image:',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.38,.48,.1],...
    'Visible', 'off');
        

%--------------------------------------------------------------------------
% creates the ROI type dropdown menu
handles.popup_maskimg = uicontrol(handles.panel_roimethod,...
    'Style','popup','Units','normalized','Position',[.01,.25,.98,.13],...
    'FontUnits','normalized','FontSize',fs*.5,'background','w');

set(handles.popup_maskimg,'String',imgnamelist,'Visible', 'off')

guidata(hObject,handles)