function save_multislices(hObject)
% save_multislices is an internal function of fMROI.
%
% Syntax:
%   save_multislices(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2023, peres.asc@gmail.com
% Last update: Andre Peres, 24/08/2023, peres.asc@gmail.com

handles = guidata(hObject);

if isfield(handles,'multiax')
    if isobject(handles.multiax(1))
        if isvalid(handles.multiax(1))

            outfilename = get(handles.edit_outscrshtpath,'string');
            [pn,fn,ext] = fileparts(outfilename);

            v = get(handles.popup_scrshtax,'Value');
            s = get(handles.popup_scrshtax,'String');
            ax_tag = s{v};

            pos = [];
            for i = 1:length(handles.multiax)
                p = GetLayoutInformation(handles.multiax(i));
                pos = [pos;p.PlotBox];
            end
            x = min(pos(:,1));
            y = min(pos(:,2));

            [xl,xli] = max(pos(:,1));
            w = (xl + pos(xli,3)) - x;

            [yl,yli] = max(pos(:,2));
            h = (yl + pos(yli,4)) - y;

            axpos = [x,y,w,h];

            ax = axes('Parent',handles.panel_graphmulti,...
                'Box','off','Units','pixels','XTick',[],'YTick',[],...
                'color','none','Position',axpos);

            f = getframe(ax);
            im = frame2im(f);

            % removes white edges generated by getframe
            im(1:2,:,:) = [];
            im(end-1:end,:,:) = [];
            im(:,1:2,:) = [];
            im(:,end-1:end,:) = [];

            outfn = fullfile(pn,[fn,'_multi',ax_tag,ext]);
            imwrite(im,outfn);

            % blink effect to indicate that the screenshot was done
            d = image(255,'Parent',ax,'AlphaData',.5);
            set(ax,'Ydir','normal','XLimMode','auto','YLimMode','auto',...
                'XTick',[],'YTick',[],...
                'Color','none','XColor','none','YColor','none');
            colormap(ax,'gray');
            pause(.1)

            delete(ax);
        end
    end
end
