function save_axes(hObject)
% save_axes is an internal function of fMROI.
%
% Syntax:
%   save_axes(hObject,~)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2023, peres.asc@gmail.com
% Last update: Andre Peres, 24/08/2023, peres.asc@gmail.com

handles = guidata(hObject);

outfilename = get(handles.edit_outscrshtpath,'string');
[pn,fn,ext] = fileparts(outfilename);

actax = [];
for i = 1:length(handles.checkbox_saveaxis)
    if handles.checkbox_saveaxis(i).Value
        actax = [actax,i];
    end
end

if isempty(actax)
    he = errordlg('Select at least one axis to proceeed!','Type Error');
    uiwait(he)
    return
end

if handles.radio_slices(2).Value
    sl2save = cell(3,1);
    for i = 1:3
        sl2save{i} = eval(['[',handles.edit_slices2save(i).String,']']);
    end
else
    sl2save = [];
end

ax_tag = {'axi','cor','sag','vol'};
for i = actax
    ax = axes('Parent',handles.panel_graph(i),...
        'Box','off','Units','normalized','XTick',[],'YTick',[],...
        'color','none','Position',[0,0,1,1]);

    if i==4 || isempty(sl2save)
        if i==4
            ss = [];
        else
            ss = get(handles.edit_pos(2,4-i),'String');
        end

        f = getframe(ax);
        im = frame2im(f);

        % removes white edges generated by getframe
        im(1:2,:,:) = [];
        im(end-1:end,:,:) = [];
        im(:,1:2,:) = [];
        im(:,end-1:end,:) = [];

        outfn = fullfile(pn,[fn,'_',ax_tag{i},ss,ext]);
        imwrite(im,outfn)

    else
        for s = sl2save{i}
            set(handles.edit_pos(2,4-i),'String',num2str(s))
            editpos_callback(handles.edit_pos(2,4-i),[])

            f = getframe(ax);
            im = frame2im(f);

            % removes white edges generated by getframe
            im(1:2,:,:) = [];
            im(end-1:end,:,:) = [];
            im(:,1:2,:) = [];
            im(:,end-1:end,:) = [];

            outfn = fullfile(pn,[fn,'_',ax_tag{i},num2str(s),ext]);
            imwrite(im,outfn)
        end
    end
    delete(ax);
end