% %--------------------------------------------------------------------------
% % creates the Welcome text
% wt = {'\bf\fontsize{14}     Welcome to fMROI Apha 1.0.0';...
%     '\fontsize{10} ';...
%     'fMROI\rm is a free software designed to create regions of';...
%     'interest (ROI) in functional magnetic resonance imaging';...
%     '(fMRI). However, it is not limited to fMRI, and can be used';...
%     'with structural images, diffusion maps (DTI), or even with';...
%     'atlases such as FreeSurfer aparc-aseg and Julich atlas.';...
%     '';...
%     'To load an image, the users have three alternatives:';...
%     '1. by clicking on \bfFile>Open menu\rm, to open a nifti file';...
%     '(functional, structural, DTI, etc.);';...
%     '2. by clicking on the menu \bfFile>Load ROI\rm to open a';...
%     'binary nifti file and automatically use it as ROI;';...
%     '3. clicking on \bfFile>Load Template\rm to open one of the';...
%     'templates installed in fMROI.';...'
%     'After loading the image, users can create and manipulate';...
%     'ROIs in the tabs at the bottom of the control panel. To';...
%     'create an ROI, the user must click on the \bfGen ROI\rm tab,';...
%     'select the method from the popup menu, adjust the';...
%     'parameters and when ready, click on the \bfGen ROI\rm button.';...
%     'After this procedure the generated ROI will appear in the';...
%     '\bfROI Table\rm tab, as well as an image will appear in the list';...
%     'of loaded images (\bfroi\_under-construction.nii\rm ).';...
%     'To save the ROIs, the user must select the \bfBin Mask\rm';...
%     'checkbox to save each ROI as an independent mask, or';...
%     '\bfAtlas+LUT\rm to save all the ROIs in the same image and ';...
%     'click on the \bfSave\rm buttom at the botton of \bfROI Table\rm tab.';...
%     '';...
%     'For the complete documentation:';...
%     'https://github.com/Proaction-Lab/fmroi'};
% 
% textwelcomepos = [0.01, 0.35, 0.98, 0.64];
% annotation(handles.panel_logo,'textbox','Position',textwelcomepos,...
%     'String',wt,'EdgeColor',[.8 .8 .8]);
% 
% % %--------------------------------------------------------------------------
% % % creates the Logo axis and text
% axeslogo_pos = [0.2545,0.12,0.4711,0.2000];
% 
% handles.axislogo = axes('Parent', handles.panel_logo,'Position',axeslogo_pos, 'Box', 'off',...
%     'Units', 'normalized','XTick', [],'YTick', []);
%             
% imshow(fullfile(fmroirootdir,'etc','figs','fmroi_logo.png'))
% 
% set(handles.axislogo, 'Tag', 'axislogo')
% 
% logocaption = {'Developed by members and colaborators of';...
%     'Proaction Lab - FPCE, University of Coimbra';...
%     'Rua do Colégio Novo - 3001-802 Coimbra, Portugal';...
%     'https://proactionlab.fpce.uc.pt'};
% 
% textlogopos = [0.01, 0.01, 0.98, 0.09];
% handles.textlogo = uicontrol(handles.panel_logo, 'Style', 'text',...
%     'Units', 'normalized', 'String', logocaption,...
%     'BackgroundColor', [1 1 1], 'FontSize', 10,...
%         'HorizontalAlignment', 'center','Position', textlogopos);