function cubicmask_gui(hObject)
% cubicmask_gui is a internal function of fMROI. It creates the panel
% and uicontrols for calling cubicmask function.
%
% Syntax:
%   cubicmask_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2019, peres.asc@gmail.com
% Last update: Andre Peres, 09/05/2022, peres.asc@gmail.com

handles = guidata(hObject);
%--------------------------------------------------------------------------
% creates the ROIs Panel
panelroi_pos = [0.01, 0.01, 0.98, 0.87];

handles.panel_roimethod = uipanel(handles.tab_genroi,...
    'BackgroundColor','w','Units','normalized',...
    'Position',panelroi_pos,'Visible','on');

%--------------------------------------------------------------------------
guidata(hObject,handles)
imgname = getselectedimgname(hObject);

handles.text_roisrcimagetxt = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String','Source image:',...
    'FontUnits','normalized','FontSize',.7,'FontWeight','bold',...
    'BackgroundColor','w','HorizontalAlignment','left',...
    'Position',[.01,.91,.3,.07]);
        
handles.text_roisrcimage = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String', imgname,...
    'FontUnits','normalized','FontSize',.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.81,.98,.07]);

%--------------------------------------------------------------------------
% creates the Radio Button Group in panel_roi  

handles.buttongroup_cubicmasktype = uibuttongroup(...
    handles.panel_roimethod,'Units','normalized',...
    'BackgroundColor','w','Position',[.01,.67,.48,.1]);
%--------------------------------------------------------------------------
% creates the cubicmasktype radio button radius
handles.radio_cubicradius = uicontrol(...
    handles.buttongroup_cubicmasktype,'Style','radiobutton',...
    'Units','normalized','String','edge','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',.8,'Position',[0,.1,.4,.8]);

%--------------------------------------------------------------------------
% creates the cubicmasktype radio button volume
handles.radio_cubicvolume = uicontrol(...
    handles.buttongroup_cubicmasktype,'Style','radiobutton',...
    'Units','normalized','String','volume','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',.8,'Position',[.5,.1,.48,.8]);

%--------------------------------------------------------------------------
% creates the text for radius/volume in voxels
handles.text_roiradius = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String','Size (voxels):',...
    'FontUnits','normalized','FontSize',.8,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.55,.24,.07]);

%--------------------------------------------------------------------------
% creates the edit text for radius/volume in voxels
handles.edit_roiradius = uicontrol(handles.panel_roimethod,...
    'Style','edit','Units','normalized','String','5',...
    'FontUnits','normalized','FontSize',.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.25,.54,.23,.08]);

guidata(hObject,handles)