function cubicmask_gui(hObject)
% cubicmask_gui is a internal function of fMROI. It creates the panel
% and uicontrols for calling cubicmask function.
%
% Syntax:
%   cubicmask_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2019, peres.asc@gmail.com
% Last update: Andre Peres, 03/08/2023, peres.asc@gmail.com

handles = guidata(hObject);
%--------------------------------------------------------------------------
% creates the ROIs Panel
fs = 1; % font scale
panelroi_pos = [0.01, 0.01, 0.98, 0.87];

handles.panel_roimethod = uipanel(handles.tab_genroi,...
    'Units','normalized','BackgroundColor','w',...
    'Position',panelroi_pos,'Visible', 'on');

%--------------------------------------------------------------------------
% creates the text for source image
guidata(hObject,handles)
imgname = getselectedimgname(hObject);

handles.text_roisrcimagetxt = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','FontWeight','bold',...
    'String','Source image:','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fs*.65,...
    'HorizontalAlignment','left','Position',[.01,.9,.98,.1]);

handles.text_roisrcimage = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String',imgname,...
    'FontUnits','normalized','FontSize',fs*.65,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.8,.98,.1]);

%--------------------------------------------------------------------------
% creates the Radio Button Group in panel_roi  

handles.buttongroup_cubicmasktype = uibuttongroup(...
    handles.panel_roimethod,'Units','normalized',...
    'BackgroundColor','w','Position',[.01,.67,.48,.11]);
%--------------------------------------------------------------------------
% creates the cubicmasktype radio button radius
handles.radio_cubicradius = uicontrol(...
    handles.buttongroup_cubicmasktype,'Style','radiobutton',...
    'Units','normalized','String','edge','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fs*.7,'Position',[0,0,.45,1]);

%--------------------------------------------------------------------------
% creates the cubicmasktype radio button volume
handles.radio_cubicvolume = uicontrol(...
    handles.buttongroup_cubicmasktype,'Style','radiobutton',...
    'Units','normalized','String','volume','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fs*.7,'Position',[.45,0,.55,1]);

%--------------------------------------------------------------------------
% creates the text for radius/volume in voxels
handles.text_roiradius = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String','Size (voxels):',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.52,.3,.1]);

%--------------------------------------------------------------------------
% creates the edit text for radius/volume in voxels
handles.edit_roiradius = uicontrol(handles.panel_roimethod,...
    'Style','edit','Units','normalized','String','5',...
    'FontUnits','normalized','FontSize',fs*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.31,.52,.18,.1]);

guidata(hObject,handles)