function drawingmask_gui(hObject)
% regiongrowingmask_gui is a internal function of fMROI. It creates the
% panel and uicontrols for calling regiongrowingmask function.
%
% Syntax:
%   regiongrowingmask_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2019, peres.asc@gmail.com
% Last update: Andre Peres, 09/05/2022, peres.asc@gmail.com

handles = guidata(hObject);
set(handles.pbutton_findmax,'Enable','off')
set(handles.pbutton_roi,'Enable','off')

if isfield(handles, 'drawingroi') &&...
        isfield(handles.drawingroi,'hroi') &&...
        ishandle(handles.drawingroi.hroi)
    delete(handles.drawingroi.hroi)
end

%--------------------------------------------------------------------------
% creates the ROIs Panel
panelroi_pos = [0.01, 0.01, 0.98, 0.87];

handles.panel_roimethod = uipanel(handles.tab_genroi, 'BackgroundColor', 'w', ...
    'Units', 'normalized', 'Position', panelroi_pos, 'Visible', 'on');

%--------------------------------------------------------------------------
% creates the text for source image
guidata(hObject,handles)
imgname = getselectedimgname(hObject);

handles.text_roisrcimagetxt = uicontrol(handles.panel_roimethod, 'Style', 'text',...
            'Units', 'normalized','FontWeight','bold', 'String', 'Source image:',...
            'BackgroundColor', 'w', 'FontSize', 9,...
            'HorizontalAlignment', 'left','Position', [0.01, 0.91, 0.3, .07]);
        
handles.text_roisrcimage = uicontrol(handles.panel_roimethod, 'Style', 'text',...
            'Units', 'normalized', 'String', imgname,...
            'BackgroundColor', 'w', 'FontSize', 9,...
            'HorizontalAlignment', 'left','Position', [0.01, 0.84, 0.98, 0.07]);

   
%--------------------------------------------------------------------------
% creates the text for ROI type dropdown menu
handles.text_workingroi = uicontrol(handles.panel_roimethod, 'Style', 'text',...
            'Units', 'normalized', 'String', 'Select the working ROI:',...
            'BackgroundColor', 'w', 'FontSize', 9,...
            'HorizontalAlignment', 'left',...
            'Position', [0.01, 0.70, 0.47, 0.1]);

%--------------------------------------------------------------------------
% creates the ROI type dropdown menu
handles.popup_workingroi = uicontrol(handles.panel_roimethod, 'Style', 'popup',...
    'Units', 'normalized','Position', [0.01, 0.62, 0.47, 0.1],...
    'background','w');

datalut = get(handles.table_roilut,'Data');
set(handles.popup_workingroi,'String',[{'new'};datalut(:,2)])

%--------------------------------------------------------------------------
% creates the text for working axis dropdown menu
handles.text_workingaxis = uicontrol(handles.panel_roimethod, 'Style', 'text',...
            'Units', 'normalized', 'String', 'Select the working axis:',...
            'BackgroundColor', 'w', 'FontSize', 9,...
            'HorizontalAlignment', 'left',...
            'Position', [0.52, 0.70, 0.47, 0.1]);        

%--------------------------------------------------------------------------
% creates the working axis dropdown menu
handles.popup_workingaxes = uicontrol(handles.panel_roimethod, 'Style', 'popup',...
    'Units', 'normalized','Position', [0.52, 0.62, 0.47, 0.1],...
    'background','w','String',{'Axial';'Coronal';'Sagittal'});

%--------------------------------------------------------------------------
% creates the text for draw freehand buttongroup
handles.text_drawingmeth = uicontrol(handles.panel_roimethod,...
            'Style','text','Units','normalized',...
            'String','Select the drawing method:','BackgroundColor','w',...
            'FontSize', 9,'HorizontalAlignment', 'left',...
            'Position', [0.01, 0.48, 0.47, 0.1]);   

%--------------------------------------------------------------------------
% creates the draw freehand buttongroup
handles.buttongroup_drawtype = uibuttongroup(handles.panel_roimethod,...
    'BackgroundColor', 'w', 'Units', 'normalized',...
    'Position', [0.01, 0.40, 0.47, 0.1]);

%--------------------------------------------------------------------------
% creates the draw freehand radio button
handles.radio_drawfreehand = uicontrol(...
    handles.buttongroup_drawtype, 'Style', 'radiobutton',...
    'Units', 'normalized','Position', [0.01, 0.1, 0.54, 0.8],...
    'String','Freehand', 'BackgroundColor', 'w',...
    'Callback',@radiobutton_drawfreehand_callback);

%--------------------------------------------------------------------------
% creates the draw polygon radio button
handles.radio_drawpolygon = uicontrol(...
    handles.buttongroup_drawtype, 'Style', 'radiobutton',...
    'Units', 'normalized','Position', [0.55, 0.1, 0.45, 0.8],...
    'String','Polygon', 'BackgroundColor', 'w',...
    'Callback',@radiobutton_drawfreehand_callback);

%--------------------------------------------------------------------------
% creates the text for the control pushbuttons
handles.text_pbutton_roidraw = uicontrol(handles.panel_roimethod,...
            'Style','text','Units','normalized',...
            'String','Drawing tools:','BackgroundColor','w',...
            'FontSize', 9,'HorizontalAlignment', 'left',...
            'Position', [0.52, 0.48, 0.47, 0.1]);   

%--------------------------------------------------------------------------
% creates the draw push button
handles.pbutton_roidraw = uicontrol(handles.panel_roimethod, 'Style', 'PushButton',...
    'Units', 'normalized','Position', [.52, .40, .11, .1],...
    'String','Draw','Callback',@pbutton_roidraw_callback);

%--------------------------------------------------------------------------
% creates the clear push button
handles.pbutton_roicleardaw = uicontrol(handles.panel_roimethod, 'Style', 'PushButton',...
    'Units', 'normalized','Position', [.64, .40, .11, .1],...
    'String','Clear','Callback',@pbutton_roicleardaw_callback);

%--------------------------------------------------------------------------
% creates the add push button
handles.pbutton_roiadd = uicontrol(handles.panel_roimethod, 'Style', 'PushButton',...
    'Units', 'normalized','Position', [.76, .40, .11, .1],...
    'String','Add','Callback',@pbutton_roiadd_callback);

%--------------------------------------------------------------------------
% creates the rem push button
handles.pbutton_roirem = uicontrol(handles.panel_roimethod, 'Style', 'PushButton',...
    'Units', 'normalized','Position', [.88, .40, .11, .1],...
    'String','Rem','Callback',@pbutton_roirem_callback);

%--------------------------------------------------------------------------
% creates the pen push button
handles.tbutton_roipen = uicontrol(handles.panel_roimethod, 'Style', 'togglebutton',...
    'Units', 'normalized','Position', [.52, .20, .44, .1],...
    'String','Pen','Callback',@tbutton_roipen_callback);

%--------------------------------------------------------------------------
% creates the edit text for radius/volume in voxels
handles.edit_brushradius = uicontrol(handles.panel_roimethod, 'Style', 'edit',...
            'Units', 'normalized', 'String', '1',...
            'BackgroundColor', 'w', 'FontSize', 11,...
            'HorizontalAlignment', 'left','Position', [.52, .05, .44, .1]);

guidata(hObject,handles)