function regiongrowingmask_gui(hObject)
% regiongrowingmask_gui is a internal function of fMROI. It creates the
% panel and uicontrols for calling regiongrowingmask function.
%
% Syntax:
%   regiongrowingmask_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2019, peres.asc@gmail.com
% Last update: Andre Peres, 09/05/2022, peres.asc@gmail.com

handles = guidata(hObject);
%--------------------------------------------------------------------------
% creates the ROIs Panel
panelroi_pos = [0.01, 0.01, 0.98, 0.87];

handles.panel_roimethod = uipanel(handles.tab_genroi, 'BackgroundColor', 'w', ...
    'Units', 'normalized', 'Position', panelroi_pos, 'Visible', 'on');

%--------------------------------------------------------------------------
% creates the text for source image
guidata(hObject,handles)
imgname = getselectedimgname(hObject);
imgnamelist = getimgnamelist(hObject);

handles.text_roisrcimagetxt = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','FontWeight','bold',...
    'String','Source image:','BackgroundColor','w','FontSize',9,...
    'HorizontalAlignment', 'left','Position', [0.01, 0.91, 0.3, .07]);

handles.text_roisrcimage = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','String', imgname,...
    'BackgroundColor', 'w', 'FontSize', 9,...
    'HorizontalAlignment','left','Position', [0.01, 0.84, 0.98, 0.07]);

%--------------------------------------------------------------------------
% creates the text for growing method dropdown menu
handles.text_growingmode = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','BackgroundColor','w',...
    'FontSize',9,'String','Select the growing method:',...
    'HorizontalAlignment', 'left',...
    'Position', [0.01, 0.70, 0.47, 0.1]);

%--------------------------------------------------------------------------
% creates the growing method dropdown menu
handles.popup_growingmode = uicontrol(handles.panel_roimethod,...
    'Style','popup','Units','normalized',...
    'background','w','Position', [0.01,0.62,0.47,0.1]);

set(handles.popup_growingmode,'String',...
    [{'ascending'};{'descending'};{'similarity'}])

%--------------------------------------------------------------------------
% creates the text for number of voxels in the ROI
handles.text_roinvox = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized','FontSize',9,...
    'String','Enter the number of voxels:',...
    'BackgroundColor','w','HorizontalAlignment','left',...
    'Position', [0.52, 0.70, 0.47, 0.1]);
        
%--------------------------------------------------------------------------
% creates the edit text for number of voxels in the ROI
handles.edit_roinvox = uicontrol(handles.panel_roimethod,...
    'Style','edit','Units','normalized','String','50',...
    'BackgroundColor','w','FontSize',11,'HorizontalAlignment','left',...
    'Position', [0.52, 0.63, 0.23, 0.09]);

%--------------------------------------------------------------------------
% creates the 'Auto' checkbox for number of voxels in the ROI
handles.checkbox_autogrowingsize = uicontrol(handles.panel_roimethod,...
    'Style','checkbox','Units','normalized',...
    'Position', [0.76, 0.63, 0.3, 0.09],...
    'String','Auto', 'BackgroundColor', 'w',...
    'Callback',@checkbox_autogrowingsize_callback);

%--------------------------------------------------------------------------
% creates the text for the intensity threshold buttongroup
handles.text_growingthrsmeth = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized',...
    'String','Select the threshold method:',...
    'BackgroundColor','w','FontSize',9,'HorizontalAlignment','left',...
    'Position', [0.01, 0.48, 0.47, 0.1]);

%--------------------------------------------------------------------------
% creates the intensity threshold dropdown menu
handles.popup_growingthrsmeth = uicontrol(handles.panel_roimethod,...
    'Style','popup','Units','normalized',...
    'background','w','Position', [0.01, 0.40, 0.31, 0.1],...
    'Callback',@popup_growingthrsmeth_callback);

set(handles.popup_growingthrsmeth,'String',[{'None'};{'Seed diff'}])


%--------------------------------------------------------------------------
% creates the intensity threshold edit text
handles.edit_growingthrsmeth = uicontrol(handles.panel_roimethod,...
    'Style','edit','Units','normalized','String','inf',...
    'BackgroundColor','w','FontSize',11,'HorizontalAlignment','left',...
    'Position',[0.325,0.41,0.145,0.09],'Enable','off');

%--------------------------------------------------------------------------
% creates the text for growingpremask Radio Button Group in panel_roi
handles.text_growingpremask = uicontrol(handles.panel_roimethod,...
    'Style','text','Units','normalized',...
    'String','Select the premask method:',...
    'BackgroundColor','w','FontSize',9,'HorizontalAlignment','left',...
    'Position', [0.52, 0.48, 0.47, 0.1]);

%--------------------------------------------------------------------------
% creates the growingpremask Radio Button Group in panel_roi
handles.buttongroup_growingpremask = uibuttongroup(...
    handles.panel_roimethod,'BackgroundColor','w',...
    'Units','normalized','Position',[0.52, 0.40, 0.47, 0.1]);

%--------------------------------------------------------------------------
% creates the imagemasktype radio button
handles.radio_growingpremaskimage = uicontrol(...
    handles.buttongroup_growingpremask, 'Style', 'radiobutton',...
    'Units', 'normalized','Position',[0.01, 0.1, 0.3, 0.8],...
    'String','Mask', 'BackgroundColor', 'w',...
    'Callback',@radiobutton_growingpremask_callback);

%--------------------------------------------------------------------------
% creates the spheremasktype radio button
handles.radio_growingpremasksphere = uicontrol(...
    handles.buttongroup_growingpremask, 'Style', 'radiobutton',...
    'Units', 'normalized','Position', [0.32, 0.1, 0.37, 0.8],...
    'String','Sphere', 'BackgroundColor', 'w',...
    'Callback',@radiobutton_growingpremask_callback);

%--------------------------------------------------------------------------
% creates the masktype 'None' radio button
handles.radio_growingpremasknone = uicontrol(...
    handles.buttongroup_growingpremask, 'Style', 'radiobutton',...
    'Units', 'normalized','Position', [0.70, 0.1, 0.3, 0.8],...
    'String','None', 'BackgroundColor', 'w',...
    'Callback',@radiobutton_growingpremask_callback);

%--------------------------------------------------------------------------
% creates the text for premask radius
handles.text_growingpremasradius = uicontrol(handles.panel_roimethod, 'Style', 'text',...
    'Units', 'normalized', 'String', 'Radius:',...
    'BackgroundColor', 'w', 'FontSize', 9,...
    'HorizontalAlignment', 'left','Position', [0.52, 0.3, 0.1, 0.07],'Visible', 'off');

%--------------------------------------------------------------------------
% creates the edit text for premask radius
handles.edit_growingpremasradius = uicontrol(handles.panel_roimethod, 'Style', 'edit',...
    'Units', 'normalized', 'String', '3',...
    'BackgroundColor', 'w', 'FontSize', 11,...
    'HorizontalAlignment', 'left','Position', [0.63, 0.3, 0.36, 0.08],'Visible', 'off');

%--------------------------------------------------------------------------
% creates the text for mask image dropdown menu
handles.text_maskimg = uicontrol(handles.panel_roimethod, 'Style', 'text',...
    'Units', 'normalized', 'String', ' Select the image for premasking:',...
    'BackgroundColor', 'w', 'FontSize', 9,...
    'HorizontalAlignment', 'left',...
    'Position', [0.01, 0.3, 0.97, 0.07]);

%--------------------------------------------------------------------------
% creates the mask image dropdown menu
handles.popup_maskimg = uicontrol(handles.panel_roimethod, 'Style', 'popup',...
    'Units', 'normalized','Position', [0.01, 0.2, 0.98, 0.1],...
    'background','w');

set(handles.popup_maskimg,'String',imgnamelist)

guidata(hObject,handles)