function popup_drawmethod_callback(hObject, ~)
% popup_drawmethod_callback is an internal function of fMROI.
%
% Syntax:
%   popup_roitype_callback(hObject, ~)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2019, peres.asc@gmail.com
% Last update: Andre Peres, 09/05/2022, peres.asc@gmail.com

handles = guidata(hObject);
fss = handles.fss; % font size scale

if isfield(handles,'panel_drawtools')
    if isobject(handles.panel_drawtools)
        if isvalid(handles.panel_drawtools)
            delete(handles.panel_drawtools)
        end
    end
end


handles.panel_drawtools = uipanel(handles.panel_roimethod,...
    'Units','normalized','BackgroundColor','w','Visible','on',...
    'Position',[.52,.01,.47,.51],'DeleteFcn',@panel_drawtools_deletefcn);

v = get(handles.popup_drawmethod,'Value');
s = get(handles.popup_drawmethod,'String');
roimth = s{v};

switch lower(roimth)
    case 'brush'

        %--------------------------------------------------------------------------
        % creates the brush tooglebutton
        handles.tbutton_brushroidraw = uicontrol(handles.panel_drawtools,...
            'Style','togglebutton','Units','normalized',...
            'String','Draw','Position',[.03,.7,.45,.25],...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@tbutton_roibrush_callback);

        %--------------------------------------------------------------------------
        % creates the brush ROI add pushbutton
        handles.pbutton_brushroiadd = uicontrol(handles.panel_drawtools,...
            'Style','PushButton','Units','normalized',...
            'String','Add','Position',[.52,.7,.45,.25],...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@pbutton_brushroiadd_callback);

        %--------------------------------------------------------------------------
        %creates the text for the control pushbuttons
        handles.text_brushradius = uicontrol(handles.panel_drawtools,...
            'Style','text','Units','normalized','String','Brush size:',...
            'FontUnits','normalized','FontSize',fss*.7,...
            'BackgroundColor','w','Position',[.03,.42,.94,.2],...
            'HorizontalAlignment','left');

        %--------------------------------------------------------------------------
        % creates the edit text for radius/volume in voxels
        handles.edit_brushradius = uicontrol(handles.panel_drawtools,...
            'Style','edit','Units','normalized','String','1',...
            'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
            'HorizontalAlignment','left','Position', [0.03, 0.22 0.94, 0.2]);

    case 'closed_shape'

        %--------------------------------------------------------------------------
        % creates the draw push button
        handles.pbutton_roidraw = uicontrol(handles.panel_drawtools,...
            'Style','PushButton','Units','normalized',...
            'String','Draw','Position',[.03,.7,.45,.25],...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@pbutton_roidraw_callback);

        %--------------------------------------------------------------------------
        % creates the add push button
        handles.pbutton_roiadd = uicontrol(handles.panel_drawtools,...
            'Style','PushButton','Units','normalized',...
            'String','Add','Position',[.52,.7,.45,.25],...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@pbutton_roiadd_callback);

        %--------------------------------------------------------------------------
        % creates the clear push button
        handles.pbutton_roicleardaw = uicontrol(handles.panel_drawtools,...
            'Style','PushButton','Units','normalized',...
            'String','Clear','Position',[.03,.4,.45,.25],...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@pbutton_roicleardaw_callback);

        %--------------------------------------------------------------------------
        % creates the rem push button
        handles.pbutton_roirem = uicontrol(handles.panel_drawtools,...
            'Style','PushButton','Units','normalized',...
            'String','Rem','Position',[.52,.4,.45,.25],...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@pbutton_roirem_callback);
                
        %--------------------------------------------------------------------------
        % creates the drawing method buttongroup
        handles.buttongroup_drawtype = uibuttongroup(...
            handles.panel_drawtools,'Units','normalized',...
            'BackgroundColor','w','Position',[.03,.1,.94,.23]);

        %--------------------------------------------------------------------------
        % creates the draw freehand radio button
        handles.radio_drawfreehand = uicontrol(...
            handles.buttongroup_drawtype,'Style','radiobutton',...
            'Units','normalized','Position',[.0,0,.54,1],...
            'String','Freehand','BackgroundColor','w',...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@radiobutton_drawfreehand_callback);

        %--------------------------------------------------------------------------
        % creates the draw polygon radio button
        handles.radio_drawpolygon = uicontrol(...
            handles.buttongroup_drawtype,'Style','radiobutton',...
            'Units','normalized','Position',[.54,0,.46,1],...
            'String','Polygon','BackgroundColor','w',...
            'FontUnits','normalized','FontSize',fss*.55,...
            'Callback',@radiobutton_drawfreehand_callback);

end

guidata(hObject,handles)
