function mosaic_gui(hObject)
% multislice_gui is an internal function of fMROI.
%
% Syntax:
%   multislice_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2023, peres.asc@gmail.com
% Last update: Andre Peres, 22/08/2023, peres.asc@gmail.com

handles = guidata(hObject);
fss = handles.fss; % font size scale

if isfield(handles,'panel_scrshtctrl')
    if isobject(handles.panel_scrshtctrl)
        if isvalid(handles.panel_scrshtctrl)
            delete(handles.panel_scrshtctrl)
        end
    end
end


%--------------------------------------------------------------------------
% creates a new blank panel screenshot controls
handles.panel_scrshtctrl = uipanel(handles.panel_tools,...
    'BackgroundColor','w','Units','normalized',...
    'Position',[.01,.09,.98,.48]);


%--------------------------------------------------------------------------GetLayoutInformation
%creates the edit text for the mosaic columns
handles.text_mosaiccol = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Columns','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.84,.32,.15],'HorizontalAlignment','right');

handles.edit_mosaiccol = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','4',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.84,.15,.15]);

%--------------------------------------------------------------------------
%creates the edit text for the mosaic lines
handles.text_mosaiclin = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Lines','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.68,.32,.15],'HorizontalAlignment','right');

handles.edit_mosaiclin = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','4',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.68,.15,.15]);

%--------------------------------------------------------------------------
%creates the edit text for the initial slice
handles.text_mosaicinitslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Init slice','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.67,.84,.32,.15],'HorizontalAlignment','left');

handles.edit_mosaicinitslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.51,.84,.15,.15]);

%--------------------------------------------------------------------------
%creates the edit text for the last slice
handles.text_mosaiclastslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Last slice','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.67,.68,.32,.15],'HorizontalAlignment','left');

handles.edit_mosaiclastslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','32',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.51,.68,.15,.15]);

%==========================================================================
%                       SLIDES BLOCK
%==========================================================================

%--------------------------------------------------------------------------
%creates the edit text for the column overlap percentage
handles.text_coloverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Col overlap','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.4,.32,.15],'HorizontalAlignment','right'); 

handles.edit_coloverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.4,.15,.15]);%,'Callback',@edit_multioverlap_callback);

%--------------------------------------------------------------------------
% creates the slider column overlap
colpos = [.57,.42,.35,.1];

handles.slider_coloverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','slider','Tag','slider_thrs','Units','normalized',...
    'Position',colpos,'Value',1);

% addlistener(handles.slider_coloverlap,'Value','PostSet',...
%     @(src,evnt)listener_coloverlap_callback...
%     (src,evnt,handles.slider_coloverlap));

 
handles.text_coloverlapmin = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','-1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor', 'w',...
    'HorizontalAlignment','right','Position',...
    [.49,...
    colpos(2)-.03,...
    colpos(1)-.5,...
    .15]);
    
handles.text_coloverlapmax = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',...
    [colpos(1)+colpos(3)+.01,...
    colpos(2)-.03,...
    .98-(colpos(1)+colpos(3)),...
    .15]);



%==========================================================================
%creates the edit text for the lines overlap percentage
handles.text_linoverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Lin overlap','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.2,.32,.15],'HorizontalAlignment','right'); 

handles.edit_linoverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.2,.15,.15]);%,'Callback',@edit_multioverlap_callback);

%--------------------------------------------------------------------------
% creates the slider column overlap
linpos = [.57,.22,.35,.1];

handles.slider_linoverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','slider','Tag','slider_thrs','Units','normalized',...
    'Position',linpos,'Value',1);

% addlistener(handles.slider_coloverlap,'Value','PostSet',...
%     @(src,evnt)listener_coloverlap_callback...
%     (src,evnt,handles.slider_coloverlap));

 
handles.text_linoverlapmin = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','-1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor', 'w',...
    'HorizontalAlignment','right','Position',...
    [.49,...
    linpos(2)-.03,...
    linpos(1)-.5,...
    .15]);
    
handles.text_linoverlapmax = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',...
    [linpos(1)+linpos(3)+.01,...
    linpos(2)-.03,...
    .98-(linpos(1)+linpos(3)),...
    .15]);

guidata(hObject,handles)
