function mosaic_gui(hObject)
% multislice_gui is an internal function of fMROI.
%
% Syntax:
%   multislice_gui(hObject)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2023, peres.asc@gmail.com
% Last update: Andre Peres, 22/08/2023, peres.asc@gmail.com

handles = guidata(hObject);
fss = handles.fss; % font size scale

if isfield(handles,'panel_scrshtctrl')
    if isobject(handles.panel_scrshtctrl)
        if isvalid(handles.panel_scrshtctrl)
            delete(handles.panel_scrshtctrl)
        end
    end
end


%--------------------------------------------------------------------------
% creates a new blank panel screenshot controls
handles.panel_scrshtctrl = uipanel(handles.panel_tools,...
    'BackgroundColor','w','Units','normalized',...
    'Position',[.01,.01,.98,.56]);


%--------------------------------------------------------------------------
%creates the edit text for the mosaic columns
handles.text_mosaiccol = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Columns','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.84,.32,.15],'HorizontalAlignment','right');

handles.edit_mosaiccol = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','4',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.84,.15,.15]);

%--------------------------------------------------------------------------
%creates the edit text for the mosaic lines
handles.text_mosaiclin = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Lines','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.68,.32,.15],'HorizontalAlignment','right');

handles.edit_mosaiclin = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','4',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.68,.15,.15]);

%--------------------------------------------------------------------------
%creates the edit text for the initial slice
handles.text_mosaicinitslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Init slice','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.67,.84,.32,.15],'HorizontalAlignment','left');

handles.edit_mosaicinitslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.51,.84,.15,.15]);

%--------------------------------------------------------------------------
%creates the edit text for the last slice
handles.text_mosaiclastslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Last slice','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.67,.68,.32,.15],'HorizontalAlignment','left');

handles.edit_mosaiclastslice = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','32',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position',[.51,.68,.15,.15]);

%--------------------------------------------------------------------------
% Creates the dropdown menu to select the axis to screenshot
handles.text_scrshtax = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Target axis','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.45,.49,.15],'HorizontalAlignment','right');


handles.popup_scrshtax = uicontrol(handles.panel_scrshtctrl,...
    'Style','popup','Units','normalized','Position',[.515,.48,.3,.13],...
    'String',{'Axial';'Coronal';'Sagittal'},...
    'FontUnits','normalized','FontSize',fss*.75,'background','w');

%==========================================================================
%                       SLIDES BLOCK
%==========================================================================

%--------------------------------------------------------------------------
%creates the edit text for the column overlap percentage
handles.text_coloverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Col overlap','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.23,.32,.15],'HorizontalAlignment','right'); 

handles.edit_coloverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.23,.15,.15],...
    'Callback',@edit_coloverlap_callback);

%--------------------------------------------------------------------------
% creates the slider column overlap
colpos = [.57,.25,.35,.1];

handles.slider_coloverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','slider','Tag','slider_mosaiccol','Units','normalized',...
    'Position',colpos,'Value',1);

addlistener(handles.slider_coloverlap,'Value','PostSet',...
    @(src,evnt)listener_mosaicoverlap_callback...
    (src,evnt,handles.slider_coloverlap));

 
handles.text_coloverlapmin = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','-1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor', 'w',...
    'HorizontalAlignment','right','Position',...
    [.49,...
    colpos(2)-.03,...
    colpos(1)-.5,...
    .15]);
    
handles.text_coloverlapmax = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',...
    [colpos(1)+colpos(3)+.01,...
    colpos(2)-.03,...
    .98-(colpos(1)+colpos(3)),...
    .15]);



%==========================================================================
%creates the edit text for the lines overlap percentage
handles.text_linoverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized',...
    'String','Lin overlap','BackgroundColor','w',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.01,.03,.32,.15],'HorizontalAlignment','right'); 

handles.edit_linoverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','edit','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','center','Position', [.34,.03,.15,.15],...
    'Callback',@edit_linoverlap_callback);

%--------------------------------------------------------------------------
% creates the slider column overlap
linpos = [.57,.05,.35,.1];

handles.slider_linoverlap = uicontrol(handles.panel_scrshtctrl,...
    'Style','slider','Tag','slider_mosaiclin','Units','normalized',...
    'Position',linpos,'Value',1);

addlistener(handles.slider_linoverlap,'Value','PostSet',...
    @(src,evnt)listener_mosaicoverlap_callback...
    (src,evnt,handles.slider_linoverlap));

 
handles.text_linoverlapmin = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','-1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor', 'w',...
    'HorizontalAlignment','right','Position',...
    [.49,...
    linpos(2)-.03,...
    linpos(1)-.5,...
    .15]);
    
handles.text_linoverlapmax = uicontrol(handles.panel_scrshtctrl,...
    'Style','text','Units','normalized','String','1',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',...
    [linpos(1)+linpos(3)+.01,...
    linpos(2)-.03,...
    .98-(linpos(1)+linpos(3)),...
    .15]);

guidata(hObject,handles)
