function connectome(hObject,~)
%
% Author: Andre Peres, 2024, peres.asc@gmail.com
% Last update: Andre Peres, 06/05/2024, peres.asc@gmail.com


delete_panel_tools(hObject)
create_panel_tools(hObject)

handles = guidata(hObject);

fss = handles.fss; % font size scale

%--------------------------------------------------------------------------
% Set the string in the title bar
set(handles.text_toolstitlebar,'string','Connectome')

%==========================================================================
% creates the text for time-series path
handles.tools.connectome.text_tspath = uicontrol(handles.panel_tools,...
    'Style','text','Units','normalized','String','Time-series path:',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.8,.4,.08]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.connectome.text_tspath);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

%--------------------------------------------------------------------------
% creates the edit text for source path
handles.tools.connectome.edit_tspath = uicontrol(handles.panel_tools,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','','FontUnits','normalized','FontSize',fss*.7,...
    'HorizontalAlignment','left','Position',[.01,.73,.92,.07]);

%--------------------------------------------------------------------------
% creates the source uigetfile pushbutton
handles.tools.connectome.pbutton_tspath = uicontrol(handles.panel_tools,...
    'Style','PushButton','Units','normalized','String','...',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.935,.73,.055,.07],...
    'Callback',@pbutton_connectomeselectfiles_callback);


%==========================================================================
% creates the text for output path
handles.tools.connectome.text_outdir = uicontrol(handles.panel_tools,...
    'Style','text','Units','normalized','String','Output folder:',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.65,.4,.08]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.connectome.text_outdir);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
        
%--------------------------------------------------------------------------
% creates the edit text for output path
handles.tools.connectome.edit_outdir = uicontrol(handles.panel_tools,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String',pwd,'FontUnits','normalized','FontSize',fss*.7,...
    'HorizontalAlignment','left','Position',[.01,.58,.92,.07]);

%--------------------------------------------------------------------------
% creates the output uiputfile pushbutton
handles.tools.connectome.pbutton_outdir = uicontrol(handles.panel_tools,...
    'Style','PushButton','Units','normalized','String','...',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.935,.58,.055,.07],...
    'Callback',@pbutton_connectomeselectfiles_callback);

%==========================================================================
% creates the run pushbutton
handles.tools.connectome.pbutton_run = uicontrol(handles.panel_tools,...
    'Style','PushButton','Units','normalized','String','Run',...
    'FontUnits','normalized','FontSize',fss*.7,...
    'Position',[.62,.26,.2,.12],'Callback',@pbutton_runconnectome_callback);

% %==========================================================================
% % creates the options checkboxes
% 
% % creates save image checkbox
% handles.tools.connectome.checkbox_saveimg = uicontrol(handles.panel_tools,...
%     'Style','checkbox','Units','normalized','String','Save masked images',...
%     'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
%     'Position',[.01,.32,.5,.08],'Value',1);
% 
% % creates save stats checkbox
% handles.tools.connectome.checkbox_savestats = uicontrol(handles.panel_tools,...
%     'Style','checkbox','Units','normalized','String','Save stats',...
%     'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
%     'Position',[.01,.24,.5,.08],'Value',1);
% 
% % creates save time-series checkbox
% handles.tools.connectome.checkbox_savets = uicontrol(handles.panel_tools,...
%     'Style','checkbox','Units','normalized','String','Save time-series',...
%     'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
%     'Position',[.01,.16,.5,.08],'Value',1,...
%     'Callback',@checkbox_savets_callback);
% 
% % creates group time-series checkbox
% handles.tools.connectome.checkbox_groupts = uicontrol(handles.panel_tools,...
%     'Style','checkbox','Units','normalized','String','Group srcimg tseries',...
%     'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
%     'Position',[.51,.16,.48,.08],'Value',0);
% 

%==========================================================================
% creates the wait bar
handles.tools.connectome.text_wb = uicontrol(handles.panel_tools,...
    'Style','text','Units','normalized','String','Ready...',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.07,.98,.07]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.connectome.text_wb);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

handles.tools.connectome.wb1 = axes(handles.panel_tools,...
    'Units','normalized','Position',[.01,.02,.98,.05],...
    'Xtick',[],'Ytick',[],'Color','w','Box','on');

handles.tools.connectome.wb2 = axes(handles.panel_tools,...
    'Units','normalized','Position',[.01,.02,0,.05],...
    'Xtick',[],'Ytick',[],'Color','b','Box','on');

guidata(hObject,handles)