function pbutton_applymasksettings_callback(hObject,~)
% pbutton_applymasksettings_callback is an internal function of fMROI.
%
% Syntax:
%   pbutton_applymasksettings_callback(hObject,~)
%
% Inputs:
%   hObject: handle of the figure that contains the fMROI main window.
%
% Author: Andre Peres, 2025, peres.asc@gmail.com
% Last update: Andre Peres, 14/05/2025, peres.asc@gmail.com

create_panel_settings(hObject)
handles = guidata(hObject);
fss = handles.fss;

%==========================================================================
% creates Butterworth filter panel
dx = 0.01;
tx = dx;
tw = (.5-3*dx)/2;
ex = 2*dx+tw;
dy = 0.04;
yed = 0.15;
th = (1-5*dy-2*yed)/4;
y = [dy+yed,2*dy+yed+th,3*dy+yed+2*th,4*dy+yed+3*th];

handles.tools.settings.checkbox_butter = uicontrol(handles.panel_settings,...
    'Style','checkbox','Units','normalized','String','Butterworth Filter:',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'Position',[0.01,.90,.24,.04],'Value',0,...
    'Callback',@checkbox_settingspanel_callback);


handles.panel_filter = uipanel(handles.panel_settings,'BackgroundColor','w',...
    'Units','normalized','Position',[0.01,.62,.48,.28]);

%--------------------------------------------------------------------------
% creates the text for TR
handles.tools.settings.text_tr = uicontrol(handles.panel_filter,...
    'Style','text','Units','normalized','String','TR (s):',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'HorizontalAlignment','right','Position',[tx,y(4),tw,th]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_tr);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for TR
handles.tools.settings.edit_tr = uicontrol(handles.panel_filter,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','1','FontUnits','normalized','FontSize',fss*.6,...
    'HorizontalAlignment','center','Position',[ex,y(4),tw,th],...
    'Callback',@updatebuttergraph);

%--------------------------------------------------------------------------
% creates the text for high-pass filter
handles.tools.settings.text_highpass = uicontrol(handles.panel_filter,...
    'Style','text','Units','normalized','String','High-pass (Hz):',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'HorizontalAlignment','right','Position',[tx,y(3),tw,th]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_highpass);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for high-pass filter
handles.tools.settings.edit_highpass = uicontrol(handles.panel_filter,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','0.001','FontUnits','normalized','FontSize',fss*.6,...
    'HorizontalAlignment','center','Position',[ex,y(3),tw,th],...
    'Callback',@updatebuttergraph);

%--------------------------------------------------------------------------
% creates the text for Loww-pass filter
handles.tools.settings.text_lowpass = uicontrol(handles.panel_filter,...
    'Style','text','Units','normalized','String','Low-pass (Hz):',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'HorizontalAlignment','right','Position',[tx,y(2),tw,th]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_lowpass);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for low-pass filter
handles.tools.settings.edit_lowpass = uicontrol(handles.panel_filter,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','0.08','FontUnits','normalized','FontSize',fss*.6,...
    'HorizontalAlignment','center','Position',[ex,y(2),tw,th],...
    'Callback',@updatebuttergraph);

%--------------------------------------------------------------------------
% creates the text for the filter order
handles.tools.settings.text_filterorder = uicontrol(handles.panel_filter,...
    'Style','text','Units','normalized','String','Order:',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'HorizontalAlignment','right','Position',[tx,y(1),tw,th]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_filterorder);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for the filter order
handles.tools.settings.edit_filterorder = uicontrol(handles.panel_filter,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','1','FontUnits','normalized','FontSize',fss*.6,...
    'HorizontalAlignment','center','Position',[ex,y(1),tw,th],...
    'Callback',@updatebuttergraph);

%--------------------------------------------------------------------------
% create axis
handles.tools.settings.axes_butter = axes('Parent',handles.panel_filter,...
    'Units','normalized','Position',[.59,.25,.38,.7]);

guidata(hObject,handles);

updatebuttergraph(hObject);

handles = guidata(hObject);

%==========================================================================
% Creates GLM regress out panel

handles.tools.settings.checkbox_regressout = uicontrol(handles.panel_settings,...
    'Style','checkbox','Units','normalized','String','GLM Regress out:',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'Position',[0.01,.53,.24,.04],'Value',0,...
    'Callback',@checkbox_settingspanel_callback);

handles.panel_regressout = uipanel(handles.panel_settings,'BackgroundColor','w',...
    'Units','normalized','Position',[0.01,.33,.48,.2]);

%--------------------------------------------------------------------------
% creates the text for counfounds path
handles.tools.settings.text_confounds = uicontrol(handles.panel_regressout,...
    'Style','text','Units','normalized','String','Confounds path:',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.82,.98,.15]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_confounds);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for confounds path
handles.tools.settings.edit_confoundspath = uicontrol(handles.panel_regressout,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','','FontUnits','normalized','FontSize',fss*.6,...
    'HorizontalAlignment','left','Position',[.01,.63,.93,.15]);

% creates the source uigetfile pushbutton
handles.tools.settings.pbutton_confoundspath = uicontrol(handles.panel_regressout,...
    'Style','PushButton','Units','normalized','String','...',...
    'FontUnits','normalized','FontSize',fss*.6,...
    'Position',[.94,.63,.05,.15],...
    'Callback',@pbutton_settingsselectfiles_callback);

%--------------------------------------------------------------------------
% creates the text for select counfounds
handles.tools.settings.text_selconf = uicontrol(handles.panel_regressout,...
    'Style','text','Units','normalized','String','Select the confounds columns:',...
    'FontUnits','normalized','FontSize',fss*.7,'BackgroundColor','w',...
    'HorizontalAlignment','left','Position',[.01,.45,.98,.15]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_selconf);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for confounds path
handles.tools.settings.edit_selconf = uicontrol(handles.panel_regressout,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','All','FontUnits','normalized','FontSize',fss*.6,...
    'HorizontalAlignment','left','Position',[.01,.26,.93,.15]);

% creates the source uigetfile pushbutton
handles.tools.settings.pbutton_selconf = uicontrol(handles.panel_regressout,...
    'Style','PushButton','Units','normalized','String','...',...
    'FontUnits','normalized','FontSize',fss*.6,...
    'Position',[.94,.26,.05,.15],...
    'Callback',@pbutton_settingsselectfiles_callback);

% creates the checkbox demean
handles.tools.settings.checkbox_demean = uicontrol(handles.panel_regressout,...
    'Style','checkbox','Units','normalized','String','Demean',...
    'FontUnits','normalized','FontSize',fss*.5,'BackgroundColor','w',...
    'Position',[.01,.02,.98,.2],'Value',1,...
    'Callback',@checkbox_demean_callback);

%==========================================================================
% creates Gaussian Smooth filter panel

handles.tools.settings.checkbox_smooth = uicontrol(handles.panel_settings,...
    'Style','checkbox','Units','normalized','String','Gaussian Smooth:',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'Position',[0.01,.24,.24,.04],'Value',0,...
    'Callback',@checkbox_settingspanel_callback);


handles.panel_smooth = uipanel(handles.panel_settings,'BackgroundColor','w',...
    'Units','normalized','Position',[0.01,.16,.48,.08]);

%--------------------------------------------------------------------------
% creates the text for FWHM
handles.tools.settings.text_fwhm = uicontrol(handles.panel_smooth,...
    'Style','text','Units','normalized','String','FWHM (mm):',...
    'FontUnits','normalized','FontSize',fss*.5,'BackgroundColor','w',...
    'HorizontalAlignment','right','Position',[.02,.2,.22,.6]);

% Java fix due uicontrol missing vertical alignment property
jh = findjobj(handles.tools.settings.text_fwhm);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

% creates the edit text for FWHM
handles.tools.settings.edit_smooth = uicontrol(handles.panel_smooth,...
    'Style','edit','Units','normalized','BackgroundColor','w',...
    'String','6','FontUnits','normalized','FontSize',fss*.5,...
    'HorizontalAlignment','center','Position',[.25,.2,.22,.6]);

%==========================================================================
% creates Gaussian z-score checkbox

handles.tools.settings.checkbox_zscore = uicontrol(handles.panel_settings,...
    'Style','checkbox','Units','normalized','String','Apply z-score',...
    'FontUnits','normalized','FontSize',fss*.6,'BackgroundColor','w',...
    'Position',[0.01,.07,.24,.04],'Value',0,...
    'Callback',@checkbox_zscore_callback);



set(handles.panel_filter,'Visible','off')
set(handles.panel_regressout,'Visible','off')
set(handles.panel_smooth,'Visible','off')

guidata(hObject,handles)
